### ISSUE TITLE
PSF-2.0 not included in recognized licenses

### ISSUE THREAD

**Issue by yawaramin** [kit-ty-kate/spdx_licenses#2]
It is included in the JSON file: https://github.com/kit-ty-kate/spdx_licenses/blob/ebc88c503f2bfb9abc4c3d7748d428e82dcda6b1/src/ids/licenses.json#L5222

However it is not in the generated OCaml code: https://github.com/kit-ty-kate/spdx_licenses/blob/ebc88c503f2bfb9abc4c3d7748d428e82dcda6b1/src/licenseIDs.ml#L369

Seems like a bug?

**Comment by kit-ty-kate** [comment]
Since https://github.com/kit-ty-kate/spdx_licenses/commit/73d6bd7c5f9b844b6e307e3b98970fdc7beecb73 the generated list is sorted by `String.compare` order.

You can see it just a couple lines above: https://github.com/kit-ty-kate/spdx_licenses/blob/ebc88c503f2bfb9abc4c3d7748d428e82dcda6b1/src/licenseIDs.ml#L363

**Comment by yawaramin** [comment]
Got it, thanks!
